// TECHNOLOGY THEME - Complete Content
// Tema: Tecnologia (computadores, software, internet, programação, smartphones, gadgets, tecnologia no trabalho)

const technologyTheme = {
    displayName: 'Tecnologia',
    
    // ============================================
    // GRAMMAR TENSES DATA - 12 TENSES
    // ============================================
    tensesData: [
        {
            name: "Present Simple",
            easy: [
                "I use the computer.",
                "She sends emails.",
                "We browse the internet.",
                "He codes every day.",
                "They download apps.",
                "I charge my phone.",
                "She updates software.",
                "We share files online.",
                "He clicks the mouse.",
                "They type quickly.",
                "I check notifications.",
                "She installs programs.",
                "We stream videos.",
                "He backs up data.",
                "They test applications.",
                "I connect devices.",
                "She deletes spam.",
                "We upload photos.",
                "He creates accounts.",
                "They scan documents.",
                "I restart systems.",
                "She edits files.",
                "We sync contacts.",
                "He searches online.",
                "They print reports.",
                "I save work.",
                "She designs graphics.",
                "We join meetings.",
                "He monitors networks.",
                "They debug errors."
            ],
            medium: [
                "I use my computer for work every day.",
                "She sends important emails to clients regularly.",
                "We browse social media during lunch breaks.",
                "He codes in Python and JavaScript daily.",
                "They download useful apps from the store.",
                "I charge my smartphone every single night.",
                "She updates all her software automatically.",
                "We share large files through cloud storage.",
                "He clicks the mouse thousands of times.",
                "They type over sixty words per minute.",
                "I check email notifications constantly throughout work.",
                "She installs security programs on all computers.",
                "We stream educational videos during training sessions.",
                "He backs up critical data to external drives.",
                "They test new applications before official deployment.",
                "I connect wireless devices to the network.",
                "She deletes spam messages from her inbox.",
                "We upload important photos to cloud storage.",
                "He creates multiple accounts for different services.",
                "They scan documents and convert them to PDF.",
                "I restart my laptop when problems occur.",
                "She edits files using professional software tools.",
                "We sync our contacts across multiple devices.",
                "He searches online for technical solutions daily.",
                "They print monthly reports for management meetings.",
                "I save my work every few minutes.",
                "She designs graphics for marketing campaigns professionally.",
                "We join video meetings with international teams.",
                "He monitors network traffic for security issues.",
                "They debug code errors before final release."
            ],
            hard: [
                "I use my powerful computer for complex data analysis and programming tasks every single day.",
                "She consistently sends dozens of professional emails to international clients throughout each business day.",
                "We browse various social media platforms and technology news websites during our brief lunch breaks.",
                "He codes proficiently in multiple programming languages including Python, JavaScript, and Java for different projects.",
                "They regularly download and test innovative applications from various app stores to stay current.",
                "I religiously charge my smartphone overnight to ensure it has sufficient battery for tomorrow's use.",
                "She meticulously updates all her software applications and operating systems to maintain optimal security.",
                "We efficiently share large video files and documents through cloud storage services with our team.",
                "He clicks his wireless mouse thousands of times daily while working on graphic design projects.",
                "They type remarkably fast at over seventy words per minute with impressive accuracy rates.",
                "I constantly check email notifications on my phone to respond to urgent messages immediately.",
                "She installs comprehensive security programs and antivirus software on all office computers regularly.",
                "We stream high-quality educational videos during training sessions to improve our technical skills.",
                "He backs up all critical data to multiple external drives following strict backup protocols.",
                "They test new applications thoroughly before official deployment to identify potential bugs early.",
                "I connect various wireless devices including printers and scanners to the office network daily.",
                "She deletes hundreds of spam messages from her inbox each morning before starting work.",
                "We upload important photos and documents to cloud storage platforms for safekeeping and accessibility.",
                "He creates multiple secure accounts for different online services to maintain privacy and organization.",
                "They scan physical documents and convert them to searchable PDF format for digital archiving.",
                "I restart my laptop immediately when performance problems occur to resolve technical issues.",
                "She edits complex files using professional software tools with advanced features and capabilities.",
                "We sync our contacts and calendars across multiple devices to maintain consistent information.",
                "He searches online forums and documentation for technical solutions to programming problems daily.",
                "They print detailed monthly reports and presentations for important management meetings regularly.",
                "I save my work every few minutes to prevent losing progress from unexpected crashes.",
                "She designs professional graphics for marketing campaigns using industry-standard design software regularly.",
                "We join video meetings with international team members across different time zones daily.",
                "He monitors network traffic patterns for security issues and potential threats continuously.",
                "They debug complex code errors systematically before the final release to ensure quality."
            ]
        },
        {
            name: "Present Continuous",
            easy: [
                "I am coding now.",
                "She is texting someone.",
                "We are watching videos.",
                "He is installing software.",
                "They are playing games.",
                "I am downloading files.",
                "She is scrolling through feeds.",
                "We are testing the app.",
                "He is debugging code.",
                "They are streaming music."
            ],
            medium: [
                "I am coding a new website feature.",
                "She is texting her colleagues about work.",
                "We are watching tutorial videos on YouTube.",
                "He is installing the latest operating system.",
                "They are playing an online multiplayer game.",
                "I am downloading important documents right now.",
                "She is scrolling through her social media feeds.",
                "We are testing the mobile app thoroughly.",
                "He is debugging complex code in the system.",
                "They are streaming their favorite music playlist."
            ],
            hard: [
                "I am carefully coding a sophisticated new feature for our company's main website application.",
                "She is currently texting several colleagues simultaneously about the upcoming important technology conference.",
                "We are actively watching detailed programming tutorial videos on YouTube to learn advanced development techniques.",
                "He is methodically installing the latest operating system update on all office computers this afternoon.",
                "They are enthusiastically playing an exciting online multiplayer game with friends from around the world.",
                "I am patiently downloading several important software updates and large documents for tomorrow's presentation.",
                "She is mindlessly scrolling through various social media feeds during her short coffee break today.",
                "We are thoroughly testing the new mobile application to identify any bugs before the official launch.",
                "He is diligently debugging extremely complex code in the banking system to fix security vulnerabilities.",
                "They are continuously streaming their carefully curated favorite music playlist while working on projects."
            ]
        },
        {
            name: "Present Perfect",
            easy: [
                "I have updated the system.",
                "She has sent the email.",
                "We have downloaded the app.",
                "He has fixed the bug.",
                "They have installed software.",
                "I have backed up files.",
                "She has reset her password.",
                "We have tested the code.",
                "He has uploaded photos.",
                "They have shared the link."
            ],
            medium: [
                "I have successfully updated the entire system.",
                "She has just sent that important email.",
                "We have already downloaded the new application.",
                "He has finally fixed the annoying bug.",
                "They have installed all necessary software programs.",
                "I have backed up all my important files.",
                "She has reset her forgotten account password.",
                "We have thoroughly tested the new code.",
                "He has uploaded hundreds of photos online.",
                "They have shared the registration link everywhere."
            ],
            hard: [
                "I have successfully updated the entire computer system to the latest version without any issues.",
                "She has just sent that critically important email to all stakeholders regarding the project deadline.",
                "We have already downloaded and installed the highly anticipated new application on all our devices.",
                "He has finally fixed the persistent annoying bug that was causing major problems for users.",
                "They have installed all necessary software programs and security updates on every computer in office.",
                "I have meticulously backed up all my important files and documents to multiple cloud storage locations.",
                "She has successfully reset her forgotten account password using the secure two-factor authentication process.",
                "We have thoroughly tested the new code multiple times to ensure it functions perfectly before deployment.",
                "He has uploaded hundreds of high-resolution photos to various online platforms for the marketing campaign.",
                "They have shared the event registration link everywhere possible including social media and email lists."
            ]
        },
        {
            name: "Present Perfect Continuous",
            easy: [
                "I have been coding all day.",
                "She has been texting nonstop.",
                "We have been browsing online.",
                "He has been gaming for hours.",
                "They have been downloading files.",
                "I have been learning Python.",
                "She has been working remotely.",
                "We have been testing software.",
                "He has been designing websites.",
                "They have been streaming videos."
            ],
            medium: [
                "I have been coding all day without breaks.",
                "She has been texting clients since this morning.",
                "We have been browsing online stores for hours.",
                "He has been gaming with friends all evening.",
                "They have been downloading large files all afternoon.",
                "I have been learning Python programming for months.",
                "She has been working remotely from home lately.",
                "We have been testing the software for weeks.",
                "He has been designing websites for five years.",
                "They have been streaming live videos all day."
            ],
            hard: [
                "I have been coding continuously all day long without taking any significant breaks from my computer.",
                "She has been texting numerous clients back and forth since early this morning about technical support issues.",
                "We have been browsing various online stores and comparison websites for hours trying to find deals.",
                "He has been gaming intensely with his international friends all evening using voice chat communication.",
                "They have been downloading massive files and software packages all afternoon due to slow internet connection.",
                "I have been diligently learning Python programming language for several months through online courses and practice.",
                "She has been successfully working remotely from her home office lately using various collaboration tools daily.",
                "We have been systematically testing the complex software application for weeks to identify all bugs.",
                "He has been professionally designing responsive websites and web applications for over five years now.",
                "They have been streaming entertaining live videos and gaming content all day to thousands of viewers."
            ]
        },
        {
            name: "Past Simple",
            easy: [
                "I bought a laptop.",
                "She developed an app.",
                "We installed the update.",
                "He fixed the computer.",
                "They launched the website.",
                "I created an account.",
                "She learned HTML.",
                "We attended a webinar.",
                "He upgraded his phone.",
                "They coded all night."
            ],
            medium: [
                "I bought a powerful new laptop yesterday.",
                "She developed a successful mobile application.",
                "We installed the important security update today.",
                "He fixed my broken computer last week.",
                "They launched their new company website online.",
                "I created a professional LinkedIn account recently.",
                "She learned HTML and CSS last summer.",
                "We attended an interesting technology webinar.",
                "He upgraded to the latest smartphone model.",
                "They coded through the entire night yesterday."
            ],
            hard: [
                "I bought a powerful new gaming laptop with the latest graphics card yesterday at the store.",
                "She successfully developed an innovative mobile application that won several prestigious industry awards last year.",
                "We quickly installed the critical security update on all company computers today before any threats appeared.",
                "He skillfully fixed my severely broken computer using specialized diagnostic tools and replacement parts last week.",
                "They successfully launched their impressive new company website with modern features online last month finally.",
                "I created a comprehensive professional LinkedIn account with detailed experience and skills listed recently online.",
                "She diligently learned HTML, CSS, and JavaScript through intensive online courses during last summer vacation completely.",
                "We enthusiastically attended an extremely interesting and informative technology webinar about artificial intelligence yesterday afternoon.",
                "He excitedly upgraded to the latest flagship smartphone model with enhanced camera and processor yesterday morning.",
                "They worked incredibly hard and coded continuously through the entire night yesterday to meet deadline."
            ]
        },
        {
            name: "Past Continuous",
            easy: [
                "I was programming yesterday.",
                "She was sending emails.",
                "We were watching Netflix.",
                "He was installing updates.",
                "They were playing online.",
                "I was debugging code.",
                "She was editing photos.",
                "We were browsing websites.",
                "He was backing up data.",
                "They were streaming content."
            ],
            medium: [
                "I was programming late into the evening.",
                "She was sending emails when I called.",
                "We were watching Netflix all afternoon long.",
                "He was installing updates during lunch break.",
                "They were playing online games together yesterday.",
                "I was debugging difficult code all morning.",
                "She was editing photos on her tablet.",
                "We were browsing various websites for research.",
                "He was backing up important data overnight.",
                "They were streaming live content all evening."
            ],
            hard: [
                "I was programming complex algorithms late into the evening when I suddenly discovered a solution.",
                "She was sending dozens of important emails when I called to discuss the urgent matter.",
                "We were comfortably watching Netflix series episodes all afternoon long before dinner time arrived yesterday.",
                "He was carefully installing critical system updates during his lunch break to avoid disrupting work.",
                "They were enthusiastically playing competitive online games together yesterday evening using voice chat constantly.",
                "I was intensely debugging extremely difficult code all morning long when I finally found the error.",
                "She was creatively editing professional photos on her tablet using advanced software during the flight.",
                "We were thoroughly browsing various technology websites for important research when the internet went down.",
                "He was methodically backing up all important company data overnight to prevent any potential data loss.",
                "They were actively streaming live gaming content all evening long to their growing audience worldwide."
            ]
        },
        {
            name: "Past Perfect",
            easy: [
                "I had saved my work.",
                "She had sent the file.",
                "We had tested the app.",
                "He had learned Java.",
                "They had upgraded already.",
                "I had downloaded it.",
                "She had fixed the issue.",
                "We had attended the course.",
                "He had installed Linux.",
                "They had backed up data."
            ],
            medium: [
                "I had saved all my work before crashing.",
                "She had sent the file before the deadline.",
                "We had tested the app before launching it.",
                "He had learned Java programming before college.",
                "They had already upgraded to Windows 11.",
                "I had downloaded the software last night.",
                "She had fixed the issue before I arrived.",
                "We had attended the online course together.",
                "He had installed Linux on his computer.",
                "They had backed up all data beforehand."
            ],
            hard: [
                "I had fortunately saved all my important work right before the computer suddenly crashed unexpectedly.",
                "She had successfully sent the large file to the client before the strict deadline expired yesterday.",
                "We had thoroughly tested the mobile application extensively before launching it to the public last week.",
                "He had completely learned Java programming language before starting college to get ahead academically.",
                "They had already upgraded all their computers to Windows 11 before the free period ended.",
                "I had wisely downloaded the necessary software last night anticipating I would need it today.",
                "She had expertly fixed the critical technical issue before I arrived at the office this morning.",
                "We had enthusiastically attended the comprehensive online course together last month to improve skills.",
                "He had successfully installed Linux operating system on his old computer to improve its performance.",
                "They had carefully backed up all important data to external drives beforehand to prevent any losses."
            ]
        },
        {
            name: "Past Perfect Continuous",
            easy: [
                "I had been coding.",
                "She had been testing.",
                "We had been downloading.",
                "He had been learning.",
                "They had been working.",
                "I had been developing.",
                "She had been designing.",
                "We had been programming.",
                "He had been streaming.",
                "They had been gaming."
            ],
            medium: [
                "I had been coding for several hours.",
                "She had been testing the software all week.",
                "We had been downloading files all morning.",
                "He had been learning Python for months.",
                "They had been working remotely since March.",
                "I had been developing the app for years.",
                "She had been designing websites all day.",
                "We had been programming together for hours.",
                "He had been streaming live for hours.",
                "They had been gaming since this morning."
            ],
            hard: [
                "I had been coding continuously for several hours when I finally solved the complex problem successfully.",
                "She had been testing the complicated software application all week before discovering the critical bug.",
                "We had been downloading enormous files all morning long when the internet connection suddenly stopped working.",
                "He had been diligently learning Python programming for several months before landing his first job.",
                "They had been working remotely from home since March when the pandemic restrictions first started.",
                "I had been developing this sophisticated mobile application for two years before releasing it publicly.",
                "She had been designing professional websites all day long when her computer crashed losing some work.",
                "We had been programming together intensely for many hours when we realized it was already midnight.",
                "He had been streaming live gaming content for over five hours when his equipment suddenly malfunctioned.",
                "They had been gaming competitively since early this morning when they finally won the tournament prize."
            ]
        },
        {
            name: "Future Simple",
            easy: [
                "I will learn to code.",
                "She will buy a laptop.",
                "We will update the system.",
                "He will develop an app.",
                "They will install software.",
                "I will upgrade my phone.",
                "She will attend the webinar.",
                "We will test the website.",
                "He will fix the bug.",
                "They will launch tomorrow."
            ],
            medium: [
                "I will learn to code in Python soon.",
                "She will buy a new laptop next week.",
                "We will update the entire system tomorrow.",
                "He will develop a mobile app this year.",
                "They will install new security software today.",
                "I will upgrade my smartphone next month.",
                "She will attend an online webinar tomorrow.",
                "We will test the new website thoroughly.",
                "He will fix the critical bug immediately.",
                "They will launch the product next week."
            ],
            hard: [
                "I will learn to code proficiently in Python and JavaScript within the next six months consistently.",
                "She will buy a powerful new laptop with advanced specifications next week for her design work.",
                "We will update the entire computer system tomorrow morning before employees arrive at the office.",
                "He will develop an innovative mobile application this year that solves common productivity problems effectively.",
                "They will install comprehensive new security software on all company devices today to prevent attacks.",
                "I will upgrade my outdated smartphone to the latest flagship model next month when available.",
                "She will attend an informative online webinar about artificial intelligence tomorrow afternoon for learning.",
                "We will thoroughly test the new website across different browsers and devices before launching it.",
                "He will fix the critical security bug immediately to prevent any potential data breaches today.",
                "They will successfully launch their innovative product next week with a comprehensive marketing campaign planned."
            ]
        },
        {
            name: "Future Continuous",
            easy: [
                "I will be coding later.",
                "She will be working remotely.",
                "We will be testing tomorrow.",
                "He will be learning Python.",
                "They will be streaming tonight.",
                "I will be developing apps.",
                "She will be attending online.",
                "We will be programming then.",
                "He will be debugging code.",
                "They will be gaming later."
            ],
            medium: [
                "I will be coding all afternoon today.",
                "She will be working remotely this week.",
                "We will be testing the system tomorrow morning.",
                "He will be learning Python programming next month.",
                "They will be streaming live tonight at eight.",
                "I will be developing mobile apps next year.",
                "She will be attending online classes this semester.",
                "We will be programming together all weekend long.",
                "He will be debugging code all day tomorrow.",
                "They will be gaming online later this evening."
            ],
            hard: [
                "I will be coding intensively all afternoon today to complete the important project deadline successfully.",
                "She will be working remotely from home office all week using various collaboration tools effectively.",
                "We will be thoroughly testing the complex system tomorrow morning to identify any remaining issues.",
                "He will be learning Python programming extensively next month through online courses and practical projects.",
                "They will be streaming live gaming content tonight at eight o'clock to their loyal audience members.",
                "I will be developing innovative mobile applications throughout next year for various client companies professionally.",
                "She will be attending challenging online computer science classes this entire semester to earn certification.",
                "We will be programming together collaboratively all weekend long to finish the urgent client project.",
                "He will be debugging complex code all day tomorrow trying to identify the source of errors.",
                "They will be gaming online together later this evening playing their favorite multiplayer games competitively."
            ]
        },
        {
            name: "Future Perfect",
            easy: [
                "I will have learned Java.",
                "She will have finished coding.",
                "We will have tested it.",
                "He will have fixed it.",
                "They will have launched it.",
                "I will have upgraded devices.",
                "She will have completed training.",
                "We will have developed the app.",
                "He will have installed everything.",
                "They will have backed up data."
            ],
            medium: [
                "I will have learned Java by next year.",
                "She will have finished coding by tonight.",
                "We will have tested everything by Friday.",
                "He will have fixed the bug by tomorrow.",
                "They will have launched the website by Monday.",
                "I will have upgraded all devices by then.",
                "She will have completed her training soon.",
                "We will have developed the app by December.",
                "He will have installed everything by morning.",
                "They will have backed up all data tonight."
            ],
            hard: [
                "I will have completely learned Java programming language by next year through consistent daily practice.",
                "She will have finished coding the entire complex project by tonight if everything goes according to plan.",
                "We will have tested everything thoroughly by Friday afternoon before the important client presentation begins.",
                "He will have fixed all critical bugs by tomorrow morning so the software can launch successfully.",
                "They will have successfully launched the new company website by Monday with all features working perfectly.",
                "I will have upgraded all office devices to the latest models by then to improve productivity.",
                "She will have completed her advanced cybersecurity training certification program very soon this month finally.",
                "We will have developed the sophisticated mobile application by December meeting all client requirements exactly.",
                "He will have installed all necessary software and security updates by morning before work starts.",
                "They will have backed up all important company data securely tonight to prevent any potential losses."
            ]
        },
        {
            name: "Future Perfect Continuous",
            easy: [
                "I will have been coding.",
                "She will have been working.",
                "We will have been testing.",
                "He will have been learning.",
                "They will have been developing.",
                "I will have been programming.",
                "She will have been designing.",
                "We will have been streaming.",
                "He will have been gaming.",
                "They will have been debugging."
            ],
            medium: [
                "I will have been coding for ten hours.",
                "She will have been working remotely for years.",
                "We will have been testing for three weeks.",
                "He will have been learning Python for months.",
                "They will have been developing for two years.",
                "I will have been programming since morning.",
                "She will have been designing websites all day.",
                "We will have been streaming for five hours.",
                "He will have been gaming all night long.",
                "They will have been debugging for days now."
            ],
            hard: [
                "I will have been coding continuously for over ten hours by the time I finish tonight.",
                "She will have been working remotely from home for three years by next month successfully.",
                "We will have been testing this complex software for three weeks by Friday when it launches.",
                "He will have been learning Python programming for six months by the time he starts job.",
                "They will have been developing this application for two years by launch date next month finally.",
                "I will have been programming since early morning for twelve hours by the time I stop tonight.",
                "She will have been designing professional websites all day long by the time she goes home.",
                "We will have been streaming live content for over five hours by the time we end broadcast.",
                "He will have been gaming competitively all night long by the time tournament finally ends tomorrow.",
                "They will have been debugging this difficult code for several days by the time solution is found."
            ]
        }
    ],

    // ============================================
    // PRONUNCIATION TECHNIQUES DATA - 7 TECHNIQUES
    // ============================================
    pronunciationData: [
        {
            name: "Word Stress Patterns",
            easy: [
                "COMputer • lapTOP",
                "SOFTware • hardWARE",
                "WEBsite • emAIL",
                "PASSword • USERname",
                "INternet • WI-fi",
                "DOWNload • UPload",
                "KEYboard • MOUse",
                "MONitor • PRINter",
                "APPle • GOOgle",
                "DESKtop • LAP-top",
                "TEXTing • BROWSing",
                "ViDEo • AUdio",
                "SERver • CLIent",
                "FOLDer • DOCument",
                "SCREENshot • HANDset"
            ],
            medium: [
                "techNOLogy • proGRAMming",
                "apliCAtion • inforMAtion",
                "deVELoper • engiNEER",
                "seciURity • priVAcy",
                "conNECtion • inSTALLation",
                "updateDATE • UPgrade",
                "smartPHONE • TABlet",
                "dataBASE • SOFTware",
                "autoMATic • elecTRONnic",
                "comPATible • acCESSible",
                "virtuAL • digiTAL",
                "processSOR • MEMory",
                "BLUEtooth • HEADphones",
                "notifiCAtion • subSCRIPtion",
                "veriVIcation • authentiCAtion"
            ],
            hard: [
                "artiFIcial inTELligence",
                "cyberseciURity • encrypTION",
                "infraSTRUCture • archiTECture",
                "develOPment • deVELoper",
                "configuraURation • instalLAtion",
                "dataVISualiation • presentaURtion",
                "commuteCAtion • collabotoRAtion",
                "optimisaZAtion • customizaZAtion",
                "authentaCAtion • verifaCAtion",
                "troubleeSHOOting • mainteURnance",
                "compatiBILity • funcationALity",
                "proGRAMming LANguage",
                "operaRATing SYStem",
                "microPROcessor • superCOMputer",
                "telecommunications • interconnection"
            ]
        },
        {
            name: "Linking Sounds",
            easy: [
                "log_in • log_out",
                "turn_on • turn_off",
                "plug_in • set_up",
                "sign_up • sign_in",
                "back_up • shut_down",
                "click_on • scroll_down",
                "type_in • print_out",
                "zoom_in • zoom_out",
                "speed_up • slow_down",
                "start_up • close_out",
                "open_up • save_as",
                "check_out • look_up",
                "power_on • boot_up",
                "hook_up • connect_to",
                "search_for • browse_through"
            ],
            medium: [
                "connect_to_wifi",
                "send_an_email",
                "download_the_app",
                "update_the_software",
                "charge_your_phone",
                "install_an_application",
                "create_a_password",
                "enter_the_code",
                "click_on_the_link",
                "upload_a_file",
                "sync_your_device",
                "reset_your_password",
                "test_the_connection",
                "delete_the_data",
                "backup_your_files"
            ],
            hard: [
                "I_need_to_update_my_software",
                "she's_downloading_an_app",
                "we're_going_to_test_it_out",
                "he_was_able_to_fix_it",
                "they_need_to_back_up_data",
                "can_you_help_me_install_this",
                "I've_got_to_charge_my_phone",
                "we_ought_to_upgrade_the_system",
                "I'll_be_able_to_code_it",
                "she_used_to_work_in_IT",
                "they_should_have_tested_it",
                "I_want_to_learn_programming",
                "we_could_have_prevented_the_bug",
                "it_seems_like_a_virus_attack",
                "I'd_like_to_ask_about_the_app"
            ]
        },
        {
            name: "Contractions Practice",
            easy: [
                "I'm online → /aɪm ˈɒnlaɪn/",
                "It's working → /ɪts ˈwɜːkɪŋ/",
                "We're coding → /wɪr ˈkəʊdɪŋ/",
                "He's debugging → /hiz diːˈbʌɡɪŋ/",
                "They're testing → /ðeər ˈtestɪŋ/",
                "I'll download it → /aɪl ˈdaʊnləʊd ɪt/",
                "You'll see → /juːl siː/",
                "She's programming → /ʃiz ˈprəʊɡræmɪŋ/",
                "We'll upgrade → /wiːl ˈʌpɡreɪd/",
                "That's brilliant → /ðæts ˈbrɪliənt/",
                "I've installed → /aɪv ɪnˈstɔːld/",
                "Don't click → /dəʊnt klɪk/",
                "Can't connect → /kɑːnt kəˈnekt/",
                "Won't work → /wəʊnt wɜːk/",
                "Doesn't load → /ˈdʌzənt ləʊd/"
            ],
            medium: [
                "I'm developing a new app → /aɪm dɪˈveləpɪŋ ə njuː æp/",
                "We're testing the software now → /wɪr ˈtestɪŋ ðə ˈsɒftweər naʊ/",
                "She's coding in Python today → /ʃiz ˈkəʊdɪŋ ɪn ˈpaɪθən təˈdeɪ/",
                "They've upgraded the system recently → /ðeɪv ˈʌpɡreɪdɪd ðə ˈsɪstəm ˈriːsntli/",
                "He'll fix the bug tomorrow → /hiːl fɪks ðə bʌɡ təˈmɒrəʊ/",
                "I'd like faster internet → /aɪd laɪk ˈfɑːstər ˈɪntənet/",
                "You shouldn't download that file → /juː ˈʃʊdənt ˈdaʊnləʊd ðæt faɪl/",
                "It's been loading for hours → /ɪts biːn ˈləʊdɪŋ fər ˈaʊərz/",
                "We haven't backed up data → /wiː ˈhævənt bækt ʌp ˈdeɪtə/",
                "They're connecting to the server → /ðeər kəˈnektɪŋ tə ðə ˈsɜːvər/",
                "I can't access my account → /aɪ kɑːnt ˈækses maɪ əˈkaʊnt/",
                "She won't answer the email → /ʃi wəʊnt ˈɑːnsər ði ˈiːmeɪl/",
                "We'll launch the website soon → /wiːl lɔːntʃ ðə ˈwebsaɪt suːn/",
                "That's what I coded yesterday → /ðæts wɒt aɪ ˈkəʊdɪd ˈjestədeɪ/",
                "You're doing excellent work today → /jɔːr ˈduːɪŋ ˈeksələnt wɜːk təˈdeɪ/"
            ],
            hard: [
                "I'd've finished coding if I'd had more time → /aɪdəv ˈfɪnɪʃt ˈkəʊdɪŋ ɪf aɪd hæd mɔːr taɪm/",
                "We shouldn't've clicked on that link → /wiː ˈʃʊdəntəv klɪkt ɒn ðæt lɪŋk/",
                "They're going to've been programming → /ðeər ˈɡəʊɪŋ təv biːn ˈprəʊɡræmɪŋ/",
                "I would've updated if you'd asked → /aɪ ˈwʊdəv ʌpˈdeɪtɪd ɪf juːd ɑːskt/",
                "She must've forgotten her password → /ʃi ˈmʌstəv fəˈɡɒtən hər ˈpɑːswɜːd/",
                "He could've fixed the bug earlier → /hiː ˈkʊdəv fɪkst ðə bʌɡ ˈɜːliər/",
                "We might've downloaded a virus → /wiː ˈmaɪtəv ˈdaʊnləʊdɪd ə ˈvaɪrəs/",
                "You shouldn't have installed that software → /juː ˈʃʊdənt həv ɪnˈstɔːld ðæt ˈsɒftweər/",
                "I'll've been coding here five years → /aɪləv biːn ˈkəʊdɪŋ hɪər faɪv jɪərz/",
                "They wouldn't've known without debugging → /ðeɪ ˈwʊdəntəv nəʊn wɪðˈaʊt diːˈbʌɡɪŋ/",
                "She'd rather've used different software → /ʃiːd ˈrɑːðərəv juːzd ˈdɪfrənt ˈsɒftweər/",
                "We can't've lost all the data → /wiː ˈkɑːntəv lɒst ɔːl ðə ˈdeɪtə/",
                "I won't've finished by tomorrow morning → /aɪ ˈwəʊntəv ˈfɪnɪʃt baɪ təˈmɒrəʊ ˈmɔːnɪŋ/",
                "You're not going to've completed testing → /jɔːr nɒt ˈɡəʊɪŋ təv kəmˈpliːtɪd ˈtestɪŋ/",
                "It could've been prevented with updates → /ɪt ˈkʊdəv biːn prɪˈventɪd wɪð ˈʌpdeɪts/"
            ]
        },
        {
            name: "Silent Letters",
            easy: [
                "des(ign) • s(cent)",
                "lis(ten) • fas(ten)",
                "w(rite) • w(rong)",
                "k(now) • k(nowledge)",
                "g(nome) • si(gn)",
                "dou(bt) • de(bt)",
                "h(our) • h(onest)",
                "w(hole) • w(rap)",
                "c(limb) • du(mb)",
                "tal(k) • wal(k)",
                "islan(d) • han(d)set",
                "tom(b) • num(b)",
                "k(nock) • k(nee)",
                "w(rist) • w(rench)",
                "mus(cle) • cas(tle)"
            ],
            medium: [
                "des(ign)er • ass(ign)ment",
                "lis(ten)ing • soft(en)ing",
                "w(rit)ing • w(rist)watch",
                "k(now)ledge • ack(now)ledge",
                "campai(g)n • foreig(n)",
                "dou(bt)ful • su(b)tle",
                "h(on)esty • exhi(b)it",
                "w(h)olesale • w(h)olesome",
                "num(b)ness • thum(b)nail",
                "tal(k)ative • wal(k)ing",
                "han(d)held • keyboar(d)",
                "autum(n) • colum(n)",
                "k(nit)ting • k(nuck)le",
                "w(rest)ling • w(rink)le",
                "Feb(r)uary • lib(r)ary"
            ],
            hard: [
                "des(ign)ation • ass(ign)ment manager",
                "lis(ten)ing dev(ice) • soft(en)ing audio",
                "w(rist)band • w(rapping) cable",
                "k(now)ledgeable • ack(now)ledgement",
                "campai(g)ning • foreig(n) server",
                "undou(b)tedly • indeB(t)edness",
                "dis(h)onest • exhi(bit)ion booth",
                "w(ho)lesaler • w(h)olesomeness",
                "num(b)ness • thum(b)nail preview",
                "wal(k)way • stal(k)ing detection",
                "han(d)shake • keyboar(d) shortcut",
                "autum(n)al • gover(n)ment data",
                "k(nit)ter • k(nowledge)ably coded",
                "w(rest)led • w(retch)edly slow",
                "Feb(r)uary • lib(r)ary management system"
            ]
        },
        {
            name: "Stress and Intonation",
            easy: [
                "I <strong>love</strong> coding.",
                "She <strong>always</strong> programs.",
                "We <strong>need</strong> faster internet.",
                "He <strong>never</strong> forgets passwords.",
                "They're <strong>very</strong> tech-savvy.",
                "I <strong>really</strong> like this app.",
                "That's <strong>exactly</strong> right.",
                "We <strong>must</strong> update now.",
                "She <strong>just</strong> installed it.",
                "It's <strong>too</strong> slow.",
                "I <strong>can't</strong> connect.",
                "That's <strong>perfect</strong> code.",
                "We're <strong>almost</strong> finished.",
                "He's <strong>completely</strong> ready.",
                "They <strong>finally</strong> launched."
            ],
            medium: [
                "I <strong>absolutely</strong> love developing mobile apps.",
                "She <strong>always</strong> writes <strong>clean</strong> efficient code.",
                "We <strong>really</strong> need faster internet connection speeds.",
                "He <strong>never</strong> forgets his complex passwords ever.",
                "They're <strong>extremely</strong> knowledgeable about technology trends.",
                "I <strong>definitely</strong> prefer programming in Python language.",
                "That's <strong>exactly</strong> the solution I was seeking.",
                "We <strong>must</strong> update our security systems <strong>immediately</strong>.",
                "She <strong>just</strong> finished installing the new software.",
                "The download speed is <strong>incredibly</strong> slow today.",
                "I <strong>simply</strong> can't connect to the <strong>wifi</strong>.",
                "That coding solution is <strong>absolutely</strong> perfect.",
                "We're <strong>nearly</strong> done with the software testing.",
                "He's <strong>completely</strong> ready for the tech presentation.",
                "They <strong>finally</strong> launched their innovative startup today."
            ],
            hard: [
                "I <strong>absolutely</strong> adore developing innovative mobile applications for <strong>clients</strong> worldwide.",
                "She <strong>consistently</strong> writes the <strong>most</strong> clean and efficient code in team.",
                "We <strong>desperately</strong> need faster and more reliable internet connection speeds <strong>now</strong>.",
                "He <strong>never</strong> forgets any of his numerous complex passwords for <strong>different</strong> accounts.",
                "They're <strong>extraordinarily</strong> knowledgeable about emerging technology trends and <strong>innovations</strong>.",
                "I <strong>strongly</strong> prefer programming in Python rather than other <strong>programming</strong> languages.",
                "That's <strong>precisely</strong> the elegant solution I was desperately <strong>searching</strong> for today.",
                "We <strong>absolutely</strong> must update our security systems before hackers <strong>attack</strong> again.",
                "She <strong>just</strong> finished successfully installing the <strong>latest</strong> version of software.",
                "The file download speed today is <strong>incredibly</strong> slow and <strong>frustratingly</strong> unstable.",
                "I <strong>simply</strong> cannot establish a stable connection to the <strong>office</strong> wifi network.",
                "That innovative coding solution is <strong>absolutely</strong> perfect and <strong>exactly</strong> what needed.",
                "We're <strong>almost</strong> completely done with comprehensive software testing <strong>finally</strong> today.",
                "He's <strong>fully</strong> prepared and <strong>completely</strong> ready for tomorrow's important tech presentation.",
                "They <strong>finally</strong> launched their groundbreaking innovative startup after <strong>years</strong> of development."
            ]
        },
        {
            name: "Minimal Pairs Training",
            easy: [
                "click • clique<br><span class='phonetic'>/klɪk/ • /kliːk/</span>",
                "chip • cheap<br><span class='phonetic'>/tʃɪp/ • /tʃiːp/</span>",
                "bit • beat<br><span class='phonetic'>/bɪt/ • /biːt/</span>",
                "ship • sheep<br><span class='phonetic'>/ʃɪp/ • /ʃiːp/</span>",
                "fill • feel<br><span class='phonetic'>/fɪl/ • /fiːl/</span>",
                "live • leave<br><span class='phonetic'>/lɪv/ • /liːv/</span>",
                "fit • feet<br><span class='phonetic'>/fɪt/ • /fiːt/</span>",
                "disk • desk<br><span class='phonetic'>/dɪsk/ • /desk/</span>",
                "email • mail<br><span class='phonetic'>/ˈiːmeɪl/ • /meɪl/</span>",
                "link • think<br><span class='phonetic'>/lɪŋk/ • /θɪŋk/</span>",
                "site • sight<br><span class='phonetic'>/saɪt/ • /saɪt/</span>",
                "byte • bite<br><span class='phonetic'>/baɪt/ • /baɪt/</span>",
                "cache • cash<br><span class='phonetic'>/kæʃ/ • /kæʃ/</span>",
                "cell • sell<br><span class='phonetic'>/sel/ • /sel/</span>",
                "code • cold<br><span class='phonetic'>/kəʊd/ • /kəʊld/"
            ],
            medium: [
                "upload • download<br><span class='phonetic'>/ˈʌpləʊd/ • /ˈdaʊnləʊd/</span>",
                "online • offline<br><span class='phonetic'>/ˈɒnlaɪn/ • /ˈɒflaɪn/</span>",
                "laptop • desktop<br><span class='phonetic'>/ˈlæptɒp/ • /ˈdesktɒp/</span>",
                "software • hardware<br><span class='phonetic'>/ˈsɒftweər/ • /ˈhɑːdweər/</span>",
                "mouse • mouth<br><span class='phonetic'>/maʊs/ • /maʊθ/</span>",
                "server • saver<br><span class='phonetic'>/ˈsɜːvər/ • /ˈseɪvər/</span>",
                "router • rooter<br><span class='phonetic'>/ˈruːtər/ • /ˈruːtər/</span>",
                "cable • able<br><span class='phonetic'>/ˈkeɪbl/ • /ˈeɪbl/</span>",
                "pixel • pickle<br><span class='phonetic'>/ˈpɪksl/ • /ˈpɪkl/</span>",
                "cursor • cancer<br><span class='phonetic'>/ˈkɜːsər/ • /ˈkænsər/</span>",
                "folder • holder<br><span class='phonetic'>/ˈfəʊldər/ • /ˈhəʊldər/</span>",
                "virus • various<br><span class='phonetic'>/ˈvaɪrəs/ • /ˈveəriəs/</span>",
                "login • log in<br><span class='phonetic'>/ˈlɒɡɪn/ • /lɒɡ ɪn/</span>",
                "update • upstate<br><span class='phonetic'>/ˌʌpˈdeɪt/ • /ˌʌpˈsteɪt/</span>",
                "backup • back up<br><span class='phonetic'>/ˈbækʌp/ • /bæk ʌp/</span>"
            ],
            hard: [
                "algorithm • logarithm<br><span class='phonetic'>/ˈælɡərɪðəm/ • /ˈlɒɡərɪðəm/</span>",
                "binary • boundary<br><span class='phonetic'>/ˈbaɪnəri/ • /ˈbaʊndri/</span>",
                "encrypt • decrypt<br><span class='phonetic'>/ɪnˈkrɪpt/ • /diːˈkrɪpt/</span>",
                "compiler • compiler<br><span class='phonetic'>/kəmˈpaɪlər/ • /kəmˈpaɪlər/</span>",
                "debugger • de-bugger<br><span class='phonetic'>/diːˈbʌɡər/ • /diː ˈbʌɡər/</span>",
                "ethernet • internet<br><span class='phonetic'>/ˈiːθənet/ • /ˈɪntənet/</span>",
                "bandwidth • band width<br><span class='phonetic'>/ˈbændwɪdθ/ • /bænd wɪdθ/</span>",
                "firewall • fire wall<br><span class='phonetic'>/ˈfaɪəwɔːl/ • /faɪə wɔːl/</span>",
                "interface • inner face<br><span class='phonetic'>/ˈɪntəfeɪs/ • /ˈɪnə feɪs/</span>",
                "malware • male wear<br><span class='phonetic'>/ˈmælweər/ • /meɪl weər/</span>",
                "protocol • proton call<br><span class='phonetic'>/ˈprəʊtəkɒl/ • /ˈprəʊtɒn kɔːl/</span>",
                "processor • process or<br><span class='phonetic'>/ˈprəʊsesər/ • /ˈprəʊses ɔːr/</span>",
                "bluetooth • blue tooth<br><span class='phonetic'>/ˈbluːtuːθ/ • /bluː tuːθ/</span>",
                "screenshot • screen shot<br><span class='phonetic'>/ˈskriːnʃɒt/ • /skriːn ʃɒt/</span>",
                "database • data base<br><span class='phonetic'>/ˈdeɪtəbeɪs/ • /ˈdeɪtə beɪs/</span>"
            ]
        },
        {
            name: "Thought Groups",
            easy: [
                "I use my computer. / I check my email. / I browse websites. / Then I start working.",
                "She writes code. / He tests software. / They fix bugs. / Everything works well.",
                "We learn programming. / We practice daily. / We solve problems. / Our skills improve.",
                "I need a new laptop. / I research online. / I compare prices. / I make my choice.",
                "He downloads apps. / He installs them. / He tries features. / Then he decides.",
                "In the morning / I check messages. / Then I code. / After that / I test.",
                "She updates software / every week. / It keeps things secure. / She stays protected.",
                "We use social media / every day. / It's our habit. / We share updates.",
                "I backup my files / regularly. / I save to cloud. / Everything is safe.",
                "They develop apps / for clients. / We deliver solutions. / Everyone is satisfied.",
                "The system is updated. / The software runs faster. / Users are happy. / Everything works.",
                "I love technology. / It makes life easier. / I learn constantly. / Progress continues.",
                "He charges devices / every night. / They work perfectly. / Battery lasts long.",
                "We connect online. / We collaborate remotely. / We work efficiently. / Projects succeed.",
                "She troubleshoots problems. / Everything functions. / She feels accomplished. / Technology works."
            ],
            medium: [
                "Every morning / I check my email inbox. / I reply to urgent messages / and organize my tasks. / Then I start / my development work.",
                "On weekdays / we usually have video calls. / We discuss project progress / and solve technical problems together. / It's our routine.",
                "My team develops software / collaboratively online. / We use version control / and review each other's code. / It's very effective.",
                "She enjoys learning / new programming languages. / She watches tutorial videos / from experienced developers. / Her skills grow constantly.",
                "After coding / we test everything thoroughly. / One person writes tests / while another reviews code. / Quality is maintained.",
                "I update my devices / at least monthly. / I install security patches / and upgrade important apps. / Then everything runs smoothly.",
                "We have daily standups / online every morning. / First we share progress / then we discuss blockers / and finally plan work.",
                "My clients request features / through our platform. / They describe requirements / and provide detailed feedback. / I implement solutions.",
                "On weekends / I learn new technologies. / I take online courses / with practical exercises. / Everyone benefits from this.",
                "She programs websites / for small businesses. / They need online presence / and modern functionality. / It's rewarding work.",
                "I secure all accounts / with strong passwords. / Two-factor authentication / protects my data. / Security matters most.",
                "We backup important data / to cloud storage. / It prevents data loss. / Files stay accessible. / Peace of mind.",
                "He troubleshoots technical issues / systematically. / It keeps systems running / and users productive. / It's his expertise.",
                "My mentor helps / every week online. / We review my code / and discuss improvements. / These sessions are invaluable.",
                "We optimize our applications / every sprint cycle. / Everyone contributes ideas. / We work efficiently. / Performance improves continuously."
            ],
            hard: [
                "My daily technology routine starts / at exactly seven in the morning. / I immediately check my smartphone / for urgent notifications and messages. / First I respond to critical emails / which sets a productive tone for the day. / Then I power up my laptop / to begin my programming work / before the morning meetings start.",
                "Every project sprint / we dedicate Monday mornings / to planning and task assignment. / We create a detailed backlog / based on client requirements and priorities. / In our video conference / we carefully discuss technical challenges / potential solutions / and realistic time estimates. / This systematic approach / helps us deliver quality software / and ensures we meet deadlines consistently.",
                "Team collaboration time / is absolutely essential for our success. / We make a conscious effort / to communicate clearly every day / regardless of time zone differences. / During standup meetings / we turn on our cameras / and focus entirely on updates. / We share progress on tickets / discuss any blocking issues / and support each other technically. / These moments strengthen our team bonds / and create efficient workflows together.",
                "My colleague absolutely loves / exploring emerging technologies / and cutting-edge frameworks. / She reads technical blogs daily / watches conference presentations / and experiments with new tools / using practical side projects. / The development environment becomes her playground / where she transforms theoretical knowledge / into working prototypes. / Our entire team benefits / from her passion for innovation / and we continuously improve / our technical capabilities every quarter.",
                "After every major deployment / we have established / a comprehensive review process. / One developer checks server logs / and monitors error rates. / Another verifies database performance / analyzing query efficiency. / Someone else tests user interfaces / across different devices and browsers. / The last person / reviews security measures / and validates access controls. / This teamwork approach / makes releases smooth and reliable / so we can quickly identify / any production issues immediately afterward.",
                "I have developed / an efficient backup strategy / that works perfectly for my needs. / Every evening automatically / my computer synchronizes files / to multiple cloud storage providers. / I categorize documents carefully / by project and importance level. / Critical code repositories / get pushed to remote servers. / Personal photos and videos / upload to secure platforms. / This organized approach / prevents catastrophic data loss / and keeps my digital life / protected and accessible always.",
                "Our established morning routine / has become highly efficient / after months of refinement. / We start with email triage / at the same time / every single day / including flexible schedules. / This consistency helps / maintain focus naturally. / After clearing urgent messages / we review our kanban board / for about fifteen minutes. / Then we begin / deep work sessions / for focused coding time / before team meetings / interrupt our concentration and flow.",
                "Junior developers on our team / have learned to code effectively / through structured mentorship and practice. / Immediately after joining / they complete onboarding tutorials / and setup development environments. / Then they work on / small bug fixes / with all documentation available. / They code independently initially / but can request code reviews / whenever they encounter difficulties. / This consistent routine / has helped them develop / excellent programming habits / and problem-solving skills / that will benefit them throughout their careers.",
                "Friday afternoons / have evolved into / a cherished learning tradition / that everyone anticipates eagerly. / Someone presents something interesting / they discovered or built / like a new JavaScript framework / or efficient algorithm. / Sometimes we explore cloud services / or discuss database optimization / with performance benchmarks. / The knowledge sharing atmosphere / engages the entire team / and everyone learns something / before the weekend begins / with its well-deserved rest.",
                "Every single evening / I read technology articles / in my comfortable home office. / This special habit / has become the highlight / of my professional development. / I choose interesting topics / from curated newsletters / and dive deep / as I learn about / emerging trends and tools. / The articles spark creativity / and help me reflect / after an productive day. / This quiet time alone / strengthens my understanding / and creates valuable insights / that I will apply / in future projects successfully.",
                "Maintaining our codebase / requires consistent daily attention / and genuine dedication throughout the year. / Each morning / before starting feature work / I review pending pull requests / with careful attention. / I thoroughly examine each change / checking for potential issues / or performance problems. / I provide constructive feedback / ensuring code quality standards. / I also refactor legacy code / that has accumulated over time. / This regular maintenance / results in healthy growing software / clean architecture / and fewer production bugs / that our users appreciate / in every release cycle.",
                "We implemented / a development workflow / that saves enormous time / during busy release periods. / Every Sunday evening / we spend two hours / planning the sprint tasks / for the entire upcoming week. / We break down user stories / into manageable subtasks. / We estimate effort required / for each item. / We assign responsibilities / to team members clearly / based on expertise and availability. / This time investment / on Sunday / eliminates confusion during sprints / and ensures everyone / has focused productive work / instead of unclear priorities / and constant context switching.",
                "Managing technical debt / might seem like / a complex ongoing challenge / but our team / approaches it systematically. / Every sprint / after completing planned features / we allocate time / for code improvements. / We identify problematic areas / through code metrics / according to quality standards. / We refactor carefully / to prevent regression bugs. / Then we add / comprehensive tests. / This consistent attention / keeps our codebase / maintainable and scalable / while also contributing / to long-term productivity / through better code quality.",
                "My mentor's weekly video calls / have become / an irreplaceable part / of my learning routine. / Every week / like clockwork / we connect / at exactly four o'clock / on Thursday afternoons. / We talk for at least / an hour or sometimes longer / discussing everything related / to software development. / He shares insights / about system design / architectural patterns / and career growth strategies. / I update him / about my coding challenges / and project accomplishments. / These regular conversations / accelerate my professional development / despite the virtual distance / between our locations. / The calls provide technical guidance / and keep my motivation strong / across different career stages.",
                "Our Saturday afternoon / hackathon sessions / transform our technical skills / from theoretical to practical. / We gather online / with energy and curiosity / ready to experiment / with new technologies. / Each team member / proposes interesting project ideas / based on passion and learning goals. / Some people explore / machine learning algorithms. / Others build / mobile applications. / I usually work / on web development projects. / Together we share / progress and discoveries. / By evening time / we have working prototypes / and we feel inspired. / This weekly experimentation / maintains a creative environment / where our team / can innovate and grow / throughout the year ahead together."
            ]
        },
{
        name: "Over-Articulation",
        displayName: "Over-Articulation (Articulação Exagerada)",
        easy: [
            "I click the mouse.",
            "She types fast.",
            "We install apps.",
            "He codes daily.",
            "They backup files.",
            "I restart the computer.",
            "She sends emails.",
            "We charge phones.",
            "He updates software.",
            "They browse websites.",
            "I delete spam.",
            "She downloads music.",
            "We connect WiFi.",
            "He designs graphics.",
            "They upload videos."
        ],
        medium: [
            "I click the mouse button very carefully now.",
            "She types incredibly fast on her new keyboard.",
            "We install useful applications every single week.",
            "He codes complex algorithms in Python language daily.",
            "They backup important files to cloud storage regularly.",
            "I restart my computer when it freezes completely.",
            "She sends professional emails to clients every morning.",
            "We charge our phones overnight for tomorrow's use.",
            "He updates all software to the latest version.",
            "They browse various websites searching for tech news.",
            "I delete spam messages from my inbox immediately.",
            "She downloads music and podcasts to her device.",
            "We connect to WiFi networks at coffee shops.",
            "He designs beautiful graphics for web development projects.",
            "They upload educational videos to YouTube channel regularly."
        ],
        hard: [
            "I click the wireless mouse button extremely carefully to avoid making accidental double-click mistakes while editing documents.",
            "She types incredibly fast on her new mechanical keyboard achieving over seventy words per minute with remarkable accuracy.",
            "We install useful productivity applications from the app store every single week to improve our workflow efficiency.",
            "He codes complex machine learning algorithms in Python programming language daily for his artificial intelligence research project.",
            "They backup all their important files and documents to multiple cloud storage services regularly to prevent data loss.",
            "I restart my computer system immediately when it freezes completely to restore normal functionality and save my work.",
            "She sends dozens of professional business emails to international clients every morning before lunch break starts at noon.",
            "We charge all our electronic devices including smartphones and tablets overnight to ensure sufficient battery for tomorrow's activities.",
            "He meticulously updates all software applications and operating systems to the latest available version for security purposes.",
            "They browse various technology news websites and forums searching for the latest information about innovative gadgets and trends.",
            "I systematically delete all spam messages and unwanted promotional emails from my inbox immediately when they arrive.",
            "She regularly downloads her favorite music albums and interesting educational podcasts to her mobile device for offline listening.",
            "We frequently connect our laptops to public WiFi networks at coffee shops and restaurants for remote work sessions.",
            "He designs beautiful user interface graphics and creates interactive animations for complex web development projects professionally.",
            "They upload engaging educational tutorial videos to their popular YouTube channel regularly to help beginners learn programming skills."
        ]
    },
    {
        name: "Tongue Twisters",
        displayName: "Tongue Twisters (Trava-Línguas)",
        easy: [
            "Smart smartphones sing.",
            "Fast flash drives.",
            "Big byte bugs.",
            "Tech text tests.",
            "Code cold clouds.",
            "Web widget works.",
            "App tap traps.",
            "Soft software sorts.",
            "Cyber cyber cycles.",
            "Click quick clips.",
            "Data data dates.",
            "Link LinkedIn links.",
            "Chip chip chips.",
            "Bug debug bugs.",
            "Cache cash clash."
        ],
        medium: [
            "Six slick smartphones sync swiftly.",
            "Peter programs Python projects perfectly.",
            "Betty better backs up bytes.",
            "Tech teachers teach text tactics.",
            "Cyber security certainly serves society.",
            "Flash drives fly fast forward.",
            "Widget Windows work wonderfully well.",
            "Sally's software syncs several servers.",
            "Cool coders code clean code carefully.",
            "Digital devices deliver data daily.",
            "Browser bugs bother busy bloggers.",
            "Smart systems store several statistics.",
            "Quick clicks create complete cached content.",
            "Virtual videos view very vividly.",
            "Modern mobile monitors monitor milliseconds."
        ],
        hard: [
            "Six slick smartphones sync swiftly with several servers simultaneously.",
            "Peter programs practical Python projects perfectly for processing purposes.",
            "Betty better backs up big binary bytes before bankruptcy.",
            "The tech teacher teaches thirty-three technology text tactics.",
            "Cyber security specialists certainly serve society seeking safety.",
            "Flash drive files fly fast forward through fiber networks.",
            "Which wicked widgets work wonderfully well with Windows?",
            "Sally's super software smoothly syncs several secure servers.",
            "Cool coders carefully code clean, clear, comprehensive computer code.",
            "Digital devices diligently deliver detailed data during daytime daily.",
            "Browser bugs badly bother busy blogging backend developers.",
            "She sells sleek systems storing several sophisticated statistical summaries.",
            "Quick clicks correctly create complete cached content continuously.",
            "Virtual reality videos visualize very vivid vast virtual vistas.",
            "Modern mobile monitoring methods measure millisecond machine movements."
        ]
    },
    {
        name: "Chunking (Natural Blocks)",
        displayName: "Chunking (Blocos Naturais)",
        easy: [
            "I use my computer / every day.",
            "She sends emails / to clients.",
            "We charge our phones / at night.",
            "He writes code / in Python.",
            "They install apps / from the store.",
            "I browse websites / for information.",
            "She updates software / regularly.",
            "We backup files / to the cloud.",
            "He designs websites / professionally.",
            "They watch videos / on YouTube.",
            "I delete spam / immediately.",
            "She types fast / on the keyboard.",
            "We connect WiFi / at home.",
            "He clicks the mouse / carefully.",
            "They download music / every week."
        ],
        medium: [
            "I use my computer / for work / every single day.",
            "She sends important emails / to international clients / regularly.",
            "We charge our phones / overnight / for tomorrow's use.",
            "He writes complex code / in Python / for data analysis.",
            "They install useful apps / from the app store / every week.",
            "I browse technology websites / searching for news / about innovations.",
            "She updates all her software / to the latest version / automatically.",
            "We backup important files / to cloud storage / every night.",
            "He designs professional websites / using modern tools / for clients.",
            "They watch educational videos / on YouTube / to learn programming.",
            "I delete spam messages / from my inbox / immediately.",
            "She types incredibly fast / on her mechanical keyboard / with accuracy.",
            "We connect to WiFi networks / at coffee shops / for remote work.",
            "He clicks the mouse button / thousands of times / during work.",
            "They download music albums / and podcasts / to their devices."
        ],
        hard: [
            "I use my powerful computer / for complex data analysis / and programming tasks / every single day.",
            "She sends dozens of emails / to international clients / throughout the business day / with great efficiency.",
            "We charge all our devices / including smartphones and tablets / overnight / to ensure sufficient battery.",
            "He writes incredibly complex code / in Python and JavaScript / for machine learning projects / professionally.",
            "They install and test / innovative applications / from various app stores / to stay current / with technology.",
            "I regularly browse / technology news websites / searching for information / about the latest innovations / and trends.",
            "She meticulously updates / all her software applications / and operating systems / to maintain security / and performance.",
            "We backup our important files / to multiple cloud services / every single night / to prevent any data loss.",
            "He designs beautiful websites / using modern frameworks / and cutting-edge tools / for demanding clients / worldwide.",
            "They watch educational tutorial videos / on YouTube channels / to learn programming languages / and development skills / effectively.",
            "I systematically delete / all spam messages / and promotional emails / from my inbox / as soon as they arrive.",
            "She types remarkably fast / on her mechanical keyboard / achieving seventy words / per minute / with impressive accuracy.",
            "We frequently connect / our laptops and devices / to public WiFi networks / at various coffee shops / for remote work.",
            "He carefully clicks / the wireless mouse button / thousands of times daily / while working on / graphic design projects.",
            "They regularly download / music albums and podcasts / to their mobile devices / for offline listening / during commutes."
        ]
    },
    {
        name: "Reading Practice",
        displayName: "Reading Practice (Prática de Leitura)",
        easy: [
            "I love technology. My smartphone is very useful. I use it every day for communication.",
            "Computers are essential today. They help us work efficiently. We cannot imagine life without them.",
            "Software updates are important. They fix bugs and improve security. I always install updates immediately.",
            "The internet connects people. We can share information instantly. Social media is very popular now.",
            "Coding is a valuable skill. Many people learn programming. It opens career opportunities worldwide.",
            "Cloud storage is convenient. I backup my files online. This protects them from computer crashes.",
            "Email communication is fast. We send messages globally. Business depends on electronic mail daily.",
            "Mobile apps are everywhere. They make life easier. I download new apps every week.",
            "WiFi networks are common. We connect at coffee shops. Internet access is essential today.",
            "Cybersecurity is crucial now. Hackers attack systems daily. We must protect our data carefully.",
            "Artificial intelligence is growing. Machines learn from data. AI will change many industries.",
            "Web development is creative. Designers build beautiful sites. Good websites attract more visitors.",
            "Video calls connect teams. Remote work is common. Technology enables collaboration from home.",
            "Smart devices are popular. They automate our homes. Technology makes life more comfortable.",
            "Digital marketing is powerful. Companies advertise online now. Social media reaches millions instantly."
        ],
        medium: [
            "Technology has transformed modern life completely. We use computers for work, education, and entertainment. Smartphones keep us connected to friends and family. Digital devices have become essential tools we cannot live without.",
            "Programming is one of the most valuable skills today. Learning to code opens countless career opportunities worldwide. Many companies need software developers urgently. Python and JavaScript are particularly popular programming languages.",
            "Cloud computing revolutionized how we store data. Instead of saving files locally on computers, we upload them to remote servers. This allows access from any device anywhere. Google Drive and Dropbox are excellent cloud storage services.",
            "Cybersecurity threats are increasing dramatically every year. Hackers constantly develop new methods to steal data. Companies invest millions in security systems and protocols. Everyone must use strong passwords and enable two-factor authentication.",
            "Artificial intelligence is changing numerous industries rapidly. Machine learning algorithms analyze massive amounts of data. AI systems can recognize faces, translate languages, and drive cars. The technology will transform society in the coming decades.",
            "Social media platforms connect billions of people globally. Facebook, Instagram, and Twitter enable instant communication and sharing. Users post photos, videos, and thoughts every second. However, privacy concerns and misinformation are growing problems.",
            "Remote work became mainstream during recent years. Video conferencing tools like Zoom enable virtual meetings. Teams collaborate effectively despite working from different locations. Many companies now offer permanent remote positions to employees.",
            "E-commerce has revolutionized retail shopping completely. Consumers buy products online with just a few clicks. Amazon and other platforms deliver items directly to homes. Traditional brick-and-mortar stores face increasing competition from digital retailers.",
            "Mobile applications dominate the software market today. Millions of apps are available on iOS and Android. People use apps for banking, fitness, navigation, and entertainment. App developers can reach global audiences through digital stores.",
            "Web development requires both creative and technical skills. Designers must understand user experience and visual aesthetics. Developers need to know HTML, CSS, JavaScript, and frameworks. Building responsive websites that work on all devices is essential.",
            "Data science is an extremely valuable field currently. Companies analyze big data to make informed decisions. Data scientists use statistics, programming, and machine learning. They discover patterns and insights that drive business strategies.",
            "Internet of Things connects everyday devices to networks. Smart homes feature automated lighting, heating, and security systems. Wearable fitness trackers monitor health continuously throughout the day. IoT technology will expand dramatically in the future.",
            "Digital marketing strategies are essential for modern businesses. Companies use SEO, social media, and content marketing. Online advertising reaches specific target audiences effectively and efficiently. Analytics tools measure campaign performance with precise metrics.",
            "Blockchain technology extends far beyond cryptocurrency applications. It provides secure, transparent, and decentralized record-keeping systems. Industries like finance, healthcare, and supply chain management are exploring blockchain solutions. The technology could revolutionize how we verify and transfer information.",
            "Virtual reality creates immersive digital experiences for users. VR headsets transport people to computer-generated environments completely. Gaming, training, and education applications are rapidly expanding. As the technology improves and becomes more affordable, adoption will increase significantly."
        ],
        hard: [
            "The technology industry has experienced unprecedented growth over the past two decades. Silicon Valley companies have become some of the world's most valuable corporations, transforming how we live, work, and communicate. Smartphones, cloud computing, artificial intelligence, and social media have fundamentally reshaped society. Today's graduates need strong technical skills to compete in the increasingly digital global economy.",
            "Software development methodologies have evolved significantly throughout computing history. Traditional waterfall approaches have largely been replaced by agile frameworks that emphasize iterative development and continuous improvement. Modern development teams use version control systems like Git, collaborate through platforms like GitHub, and deploy applications using sophisticated DevOps pipelines. Understanding these contemporary practices is absolutely essential for aspiring programmers.",
            "Cybersecurity has become one of the most critical concerns for organizations worldwide. Sophisticated cyberattacks target governments, corporations, and individuals daily, seeking to steal sensitive data, disrupt operations, or demand ransom payments. Security professionals must constantly update their knowledge to defend against evolving threats. Multi-factor authentication, encryption, and employee training programs form the foundation of comprehensive security strategies.",
            "Artificial intelligence and machine learning are revolutionizing countless industries simultaneously. Healthcare systems use AI to diagnose diseases and recommend treatments with remarkable accuracy. Financial institutions deploy algorithms to detect fraudulent transactions in real-time. Autonomous vehicles process sensor data to navigate complex environments safely. As computational power increases and datasets grow larger, AI capabilities will continue to expand exponentially in the coming years.",
            "Cloud computing platforms have transformed how organizations deploy and manage their IT infrastructure. Rather than maintaining expensive on-premises data centers, companies can now rent computing resources on-demand from providers like Amazon Web Services, Microsoft Azure, and Google Cloud Platform. This shift enables unprecedented scalability, reduces capital expenditures, and allows businesses to focus on their core competencies instead of managing servers and networks.",
            "The smartphone revolution has fundamentally changed human behavior and communication patterns. These powerful pocket computers provide instant access to information, entertainment, and social connections anywhere, anytime. Mobile-first design has become standard practice for software developers creating applications. However, concerns about technology addiction, privacy violations, and the psychological impacts of constant connectivity have emerged as significant societal challenges requiring thoughtful solutions.",
            "Remote work technology has matured dramatically, enabling distributed teams to collaborate effectively across continents. Video conferencing platforms, project management tools, and cloud-based document sharing systems replicate many aspects of traditional office environments. The COVID-19 pandemic accelerated this transformation, proving that many jobs can be performed remotely without productivity losses. Many experts predict that hybrid work models combining remote and in-office time will become the new standard.",
            "Data science has emerged as a critical discipline at the intersection of statistics, programming, and domain expertise. Organizations collect massive amounts of data from customers, operations, and external sources, but raw data alone provides little value. Data scientists clean, analyze, and visualize this information to extract actionable insights that inform strategic decisions. Proficiency in programming languages like Python and R, along with strong mathematical foundations, are essential for success in this field.",
            "The Internet of Things ecosystem continues expanding as more devices gain internet connectivity and sensing capabilities. Smart home systems control lighting, temperature, and security remotely through smartphone applications. Industrial IoT sensors monitor manufacturing equipment to predict maintenance needs and prevent costly breakdowns. Wearable fitness trackers continuously collect health data, providing users with detailed insights about their physical activity and sleep patterns. As costs decrease and standards mature, IoT adoption will accelerate.",
            "Blockchain technology represents a paradigm shift in how we establish trust and verify transactions without centralized authorities. While cryptocurrency applications like Bitcoin initially popularized blockchain, the underlying distributed ledger technology has far broader potential applications. Supply chain systems can track product provenance with unprecedented transparency. Healthcare networks can share patient records securely while maintaining privacy. Smart contracts automatically execute agreements when predefined conditions are met, reducing the need for intermediaries.",
            "Web development has evolved into a highly sophisticated discipline requiring mastery of numerous technologies and frameworks. Modern websites must be responsive, accessible, secure, and performant across diverse devices and network conditions. Frontend developers work with HTML, CSS, and JavaScript frameworks like React, Angular, or Vue to create interactive user interfaces. Backend developers build server-side logic, manage databases, and create APIs that power applications. Full-stack developers possess expertise across both domains.",
            "Digital transformation initiatives are reshaping traditional business models across every industry sector. Companies that fail to embrace technological innovation risk becoming obsolete as more agile competitors leverage digital tools to improve efficiency, enhance customer experiences, and create new revenue streams. Successfully executing digital transformation requires not only implementing new technologies but also transforming organizational culture, processes, and leadership approaches. Change management and employee training programs are absolutely critical for success.",
            "Open source software has become the foundation of modern technology infrastructure. Collaborative development models enable programmers worldwide to contribute to shared codebases, accelerating innovation and improving software quality through peer review. Major projects like Linux, Apache, and Kubernetes power much of the internet and cloud computing infrastructure. Companies increasingly embrace open source philosophies, recognizing that sharing certain technologies publicly can accelerate ecosystem development while still maintaining competitive advantages in other areas.",
            "Virtual and augmented reality technologies are creating entirely new categories of immersive experiences. VR headsets transport users to completely computer-generated environments for gaming, training simulations, and virtual tourism. Augmented reality overlays digital information onto the physical world through smartphone cameras or specialized glasses. These technologies have applications in education, healthcare, engineering, and entertainment. As hardware becomes more affordable and content libraries expand, mainstream adoption will accelerate significantly over the next decade.",
            "Quantum computing represents a revolutionary approach to information processing that could solve currently intractable problems. Unlike classical computers that use binary bits, quantum computers exploit quantum mechanical phenomena like superposition and entanglement to perform certain calculations exponentially faster. While practical quantum computers remain in early development stages, researchers are making steady progress. Applications may include drug discovery, cryptography, financial modeling, and optimization problems. The technology could fundamentally transform industries in profound ways."
        ]
    }]
};

// Export the theme object
// To use in your app: import or copy this entire object
